### ISSUE TITLE
Use of relative paths

### ISSUE THREAD

**Issue by JTrossen** [omar-dulaimi/breakpoint-bookmarks#1]
The breakpoints are saved in a corresponding file in the .vscode directory. These files contains the locations of the breakpoints, which is specified as an absolute path. 

It would be very helpful if relative pahts would also work, so the files could be used for collaboration.

**Comment by omar-dulaimi** [comment]
Released in 1.1.0

Please give it a try and, if you can, consider sponsoring me for continued support and features :)
