### ISSUE TITLE
Mismatch for breakpoint linenumber

### ISSUE THREAD

**Issue by JTrossen** [omar-dulaimi/breakpoint-bookmarks#2]
There is a mismatch between the breakpoint linenumber from the file and die brakepoint at the sourcecode.  See attachment. 

It would be helpful if both linenumbers were same. This would allow to insert the linenumber manually in the file.
![Screenshot from 2023-01-30 13-54-03](https://user-images.githubusercontent.com/112926677/215484577-951ed044-99f7-4ae3-ab7d-37153b1cee72.png)

**Comment by omar-dulaimi** [comment]
I think this happens because numbers start from 0 in vscode APIs but the UI start from one. As a quick workaround, you can try incrementing the manual values by 1. In the editor UI the line number is 26, so in the code it should be 25.

**Comment by JTrossen** [comment]
That was my assumption too, but I was still hoping that it would be possible to have a one-to-one mapping.

**Comment by omar-dulaimi** [comment]
Released in 1.0.0

Please wait sometime until it's available on the marketplace. Also, consider sponsoring me for continued development on this extension and more soon :)
