### ISSUE TITLE
How to delete saved bookmark?

### ISSUE THREAD

**Issue by dgutiero97** [omar-dulaimi/breakpoint-bookmarks#3]

**Comment by dimateos** [comment]
You can delete the json inside .vscode/breakpoints/

But would be nice to have a simple button to delete on deman like:

![image](https://github.com/omar-dulaimi/breakpoint-bookmarks/assets/26868611/0c29b7f3-5e13-4028-85ca-047ddcf120ee)

> Pic from a similar extension, settings.preset: https://marketplace.visualstudio.com/items?itemName=legendmaster.settings-presets

**Comment by omar-dulaimi** [comment]
I'll try to include this feature in the next release, but until then you can delete it manually as @dimateos suggested

Apologies for the delay in responding

**Comment by omar-dulaimi** [comment]
@dgutiero97 @dimateos 

Released & published in 1.2.0

Should be available on the marketplace in a few minutes
